[messages]
	unable_to_use = "messages.koko.unable_to_use"
	unable_to_attack = "messages.koko.unable_to_attack"
	unable_to_consume = "messages.koko.unable_to_consume"
	unable_to_craft = "messages.koko.unable_to_craft"
	unable_to_forge = "messages.koko.unable_to_forge"
	unable_to_armor = "messages.koko.unable_to_armor"
	curios_unable_to_wear = "messages.koko.curios_unable_to_wear"
	iss_unable_to_cast = "messages.koko.iss_unable_to_use"
	iss_unable_to_inscribe = "messages.koko.iss_unable_to_inscribe"
